### ISSUE TITLE
Push builds into GCR

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#140]
We build a Docker image and push it to AWS for use in the production app, but this sits inside a private ECR repository. 

It could be useful to have the image on a public repo as well. Based on the work from cal-itp/eligibility-server#22, we can add an additional `docker/build-push-action` step to our `dev` deployment that pushes into the GitHub Container Registry:

```yaml
- name: Build and push main
  uses: docker/build-push-action@v2
  if: ${{ github.event_name != 'release' }}
  with:
    push: true
    tags: ghcr.io/${{github.repository}}:<branch>
```

We can do this for each of our 3 environments to always have the current image running in each environment, available in GCR as well.

Since #135 landed, additional `docker/build-push-action` steps should go very fast.
