### ISSUE TITLE
Only run terraform pipeline for changes to terraform files

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#1736]
E.g. under `triggers`:

```yaml
  # only run for changes to Terraform files
  paths:
    include:
      - terraform/*
```

See https://github.com/cal-itp/eligibility-server/blob/dev/terraform/pipeline/azure-pipelines.yml#L11

**Comment by thekaveman** [comment]
Wait we already have this filter? 

https://github.com/cal-itp/benefits/blob/dev/terraform/azure-pipelines.yml#L12

**Comment by angela-tran** [comment]
> Wait we already have this filter?
> 
> https://github.com/cal-itp/benefits/blob/dev/terraform/azure-pipelines.yml#L12

That only applies to the `trigger` section which covers `branches` and `tags`. (In Azure docs, this section is referred to as [CI triggers](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers).)

At the same level as `trigger`, you _can_ define a `pr` section which will need its own `path` filter section. If you omit the `pr` section, it is treated the same as if you defined:
```
pr:
  branches:
    include:
    - '*'
```

which does not have a path filter.
