### ISSUE TITLE
Create issue template for Design

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#569]
GitHub recommends using the newer [Issue Forms syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms), a simple YAML-based structure.

```yaml
name: Design
labels: ["design"]
assignees:
  - srhhnry
  - Indiajar
```
