### ISSUE TITLE
Update dev deploy to push into Azure

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#586]
https://docs.microsoft.com/en-us/azure/app-service/deploy-best-practices#use-github-actions

* [ ] [Create a service principal and add it as a GitHub secret](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#create-a-service-principal-and-add-it-as-a-github-secret)
* [ ] Add a step to `deploy-dev.yaml` to authenticate to Azure:

    ```yaml
    - name: Authenticate using a Service Principal
      uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    ```
* [ ] Add a step to `deploy-dev.yaml` to update the app service:

    ```yaml
    - name: Update image tag on the Azure Web App
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: '<your-webapp-name>'
        slot-name: '<your-slot-name>'
        images: '<your-image>:<your-tag>'
    ```
